"use client";
import Image from "next/image";
import dynamic from "next/dynamic";
import { useEffect, useRef, useState } from "react";
import { Icon, Logo } from "@/components/brand";
const QuizDialog = dynamic(() => import("@/components/quiz-dialog"), { ssr: false, loading: () => <div className="opening-indicator" role="status">Opening your quiz…</div> });

const faqs = [
  ["Is this my actual financial worth?", "No. WorthMe is an entertainment experience. The score and value are playful, fictional results—not financial, professional, or psychological assessments."],
  ["Do I need to pay or create an account?", "No. The current experience is free, with no account and no payment details required."],
  ["Is the result generated by AI?", "No. WorthMe selects from 100 prewritten result combinations using your answers. There is no AI service involved."],
  ["What will other people see?", "Your share card contains your display name, optional photo, score, and playful verdict. Your age, income, city, profession, and goal are not included as public fields. Anyone with the link can open the card."],
  ["Can I skip the photo?", "Absolutely. Your card gets a colourful initial instead. If you add a photo, it is compressed before saving."],
];
export default function Home() {
  const [quizOpen, setQuizOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const menuButton = useRef<HTMLButtonElement>(null);
  useEffect(() => {
    if (!("IntersectionObserver" in window)) return;
    const motion = window.matchMedia("(prefers-reduced-motion: reduce)");
    const elements = document.querySelectorAll<HTMLElement>("[data-reveal]");
    const observer = new IntersectionObserver(entries => entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.remove("reveal-pending");
        entry.target.classList.add("is-revealed");
        observer.unobserve(entry.target);
      }
    }), { threshold: 0.08 });
    function observe() {
      observer.disconnect();
      elements.forEach(element => {
        element.classList.remove("reveal-pending");
        if (!motion.matches && !element.classList.contains("is-revealed")) {
          if (element.getBoundingClientRect().top >= window.innerHeight) element.classList.add("reveal-pending");
          observer.observe(element);
        }
      });
    }
    observe();
    motion.addEventListener("change", observe);
    return () => {
      observer.disconnect();
      motion.removeEventListener("change", observe);
      elements.forEach(element => element.classList.remove("reveal-pending"));
    };
  }, []);
  useEffect(() => {
    if (!menuOpen) return;
    function escape(event: KeyboardEvent) {
      if (event.key === "Escape") { setMenuOpen(false); menuButton.current?.focus(); }
    }
    document.addEventListener("keydown", escape);
    return () => document.removeEventListener("keydown", escape);
  }, [menuOpen]);
  function openQuiz() { setMenuOpen(false); setQuizOpen(true); }
  return <div className="site-shell">
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header"><nav className="site-nav" aria-label="Main navigation">
      <a href="#main" aria-label="WorthMe home"><Logo priority /></a>
      <div className="nav-links"><a href="#how">How it works</a><a href="#why">Why WorthMe?</a><a href="#faqs">FAQs</a></div>
      <div className="nav-actions"><button className="nav-cta" onClick={openQuiz} aria-haspopup="dialog">Find My Worth <Icon name="arrow" /></button><button ref={menuButton} className="icon-button menu-toggle" aria-label={menuOpen ? "Close navigation" : "Open navigation"} aria-expanded={menuOpen} aria-controls="mobile-navigation" onClick={() => setMenuOpen(!menuOpen)}><Icon name={menuOpen ? "close" : "menu"} /></button></div>
    </nav><nav id="mobile-navigation" className="mobile-navigation" aria-label="Mobile navigation" hidden={!menuOpen} onClick={() => setMenuOpen(false)}><a href="#how">How it works <span>01</span></a><a href="#why">Why WorthMe? <span>02</span></a><a href="#faqs">FAQs <span>03</span></a></nav></header>
    <main id="main">
      <section className="brand-hero" aria-labelledby="hero-title">
        <div className="hero-copy">
          <p className="hero-pill"><span /> A LITTLE CURIOSITY LOOKS GOOD ON YOU</p>
          <h1 id="hero-title"><span>Big potential.</span><span>But what’s</span><span>your <mark>worth?</mark></span></h1>
          <p className="hero-lead">45 seconds. A fresh perspective. An unnecessarily serious valuation of a wonderfully complicated you.</p>
          <div className="hero-actions"><button className="primary-button" onClick={openQuiz} aria-haspopup="dialog">Reveal my worth <Icon name="arrow" /></button><a className="hero-secondary" href="#how">How it works <span aria-hidden="true">&#8600;</span></a></div>
          <div className="hero-benefits"><span><Icon name="clock" />45 seconds</span><span><Icon name="shield" />No sign-up</span><span><Icon name="spark" />100% for fun</span></div>
        </div>
        <div className="hero-stage">
          <span className="stage-label">THE YOU, REIMAGINED EDITION <span>NO. 001</span></span>
          <span className="stage-spark spark-one" aria-hidden="true"><Icon name="spark" /></span><span className="stage-spark spark-two" aria-hidden="true"><Icon name="spark" /></span>
          <div className="hero-halo" aria-hidden="true" /><div className="hero-orbit" aria-hidden="true" />
          <Image className="hero-person" src="/brand/hero-thinker.png" alt="A curious young professional looking toward a new perspective" width={1024} height={1536} priority sizes="(max-width: 600px) 75vw, (max-width: 900px) 440px, 480px" />
          <div className="potential-tag"><Icon name="spark" /><span>Same person.<strong>Bigger potential.</strong></span></div>
          <article className="hero-score-card" aria-label="Example WorthMe result">
            <div className="preview-top"><span className="mini-brand">Worth<mark>Me</mark></span><span className="sample-label">SAMPLE</span></div>
            <p className="preview-label">YOUR WORTH SCORE</p><div className="preview-score"><strong>87</strong><span>/ 100</span><Icon name="spark" /></div>
            <div className="preview-type">The Intentional Builder</div>
            <div className="preview-bars"><div><span>Brain power</span><i><b style={{ transform: "scaleX(.87)" }} /></i><strong>87</strong></div><div><span>Potential</span><i><b style={{ transform: "scaleX(.94)" }} /></i><strong>94</strong></div><div><span>People value</span><i><b style={{ transform: "scaleX(.91)" }} /></i><strong>91</strong></div></div>
            <p className="preview-caption">Big ideas. A little chaos. Plenty of possibility.</p>
          </article>
          <span className="hero-caption">A conversation starter, made for you.</span>
        </div>
      </section>
      <div className="brand-ribbon" aria-label="Discover, laugh, improve"><span>DISCOVER.</span><Icon name="spark" /><span>LAUGH.</span><Icon name="spark" /><span>IMPROVE.</span><Icon name="spark" /><span className="ribbon-note">A new way to see yourself.</span></div>
      <section id="how" className="how-section section-shell" aria-labelledby="how-title">
        <div className="section-heading" data-reveal><p className="eyebrow">SMALL INPUT. BIG MAIN-CHARACTER ENERGY.</p><h2 id="how-title">From “just curious”<br />to “that’s so me.”</h2><p>Three little steps to a different point of view.</p></div>
        <div className="steps-grid">
          <article data-reveal><div className="step-top"><span>01</span><Icon name="camera" /></div><h3>A little about you.</h3><p>Add your profile and a few quick details. Your photo is completely optional.</p><span className="step-caption">THE INTRODUCTION</span></article>
          <article data-reveal><div className="step-top"><span>02</span><Icon name="spark" /></div><h3>Your plot twist.</h3><p>Meet your worth score, personality type, and one small idea for your next chapter.</p><span className="step-caption">THE REVEAL</span></article>
          <article data-reveal><div className="step-top"><span>03</span><Icon name="share" /></div><h3>Pass the curiosity.</h3><p>Download your card or share its link. Give the group chat something to talk about.</p><span className="step-caption">THE CONVERSATION</span></article>
        </div>
      </section>
      <section id="why" className="worth-experience section-shell" aria-labelledby="why-title">
        <div className="experience-orbit" aria-hidden="true" />
        <div className="experience-intro" data-reveal><p className="eyebrow">THE WORTHME DIFFERENCE</p><h2 id="why-title">More perspective.<br /><mark>Less pressure.</mark></h2><p>You’re more than a number. This one just happens to come with a grin.</p></div>
        <div className="experience-track">
          <article className="experience-card private-card" data-reveal><span className="experience-number">01 / PERSONAL</span><Icon name="shield" /><h3>Your story.<br />Your choice.</h3><p>Your raw answers stay off the share card. You choose where its link goes.</p></article>
          <article className="experience-card playful-card" data-reveal><span className="experience-number">02 / PLAYFUL</span><Icon name="spark" /><h3>Made for<br />a little grin.</h3><p>100 prewritten result combinations. One light-hearted moment that’s yours.</p></article>
          <article className="experience-card share-card" data-reveal><span className="experience-number">03 / SHAREABLE</span><Icon name="share" /><h3>Too good for<br />the camera roll.</h3><p>A personal card, a shareable link, and an excellent excuse to challenge a friend.</p></article>
        </div><p className="experience-signoff">DISCOVER. LAUGH. IMPROVE. <span>Repeat as curious.</span></p>
      </section>
      <section id="faqs" className="faq-section section-shell" aria-labelledby="faq-title">
        <div className="section-heading" data-reveal><p className="eyebrow">A FEW GOOD QUESTIONS</p><h2 id="faq-title">Curiosity,<br />cleared up.</h2><p>A little context before your close-up.</p></div>
        <div className="faq-list">{faqs.map(([question, answer]) => <details key={question} data-reveal><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div>
      </section>
      <section className="closing-section section-shell" aria-labelledby="closing-title" data-reveal>
        <div className="closing-stamp" aria-hidden="true"><Icon name="spark" /><span>100% YOU<br />100% FOR FUN</span></div>
        <div><p className="eyebrow">YOUR NEXT PLOT TWIST STARTS HERE</p><h2 id="closing-title">A little curious?<br />A lot of <em>potential.</em></h2><p>Meet your score. Keep the perspective. Pass on the grin.</p><button className="primary-button" onClick={openQuiz} aria-haspopup="dialog">Let's find out <Icon name="arrow" /></button><span className="closing-note">Free. 45 seconds. Wonderfully you.</span></div>
      </section>
      <noscript><p className="noscript-note section-shell">Enable JavaScript in your browser to take the WorthMe quiz. You can still explore how it works and read our FAQs.</p></noscript>
    </main>
    <footer className="site-footer"><a href="#main" aria-label="WorthMe home"><Logo /></a><nav aria-label="Footer"><a href="#how">About</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="#faqs">FAQs</a></nav><p>Made with curiosity in India.<span>For entertainment. For adults 18+.</span></p></footer>
    {quizOpen && <QuizDialog onClose={() => setQuizOpen(false)} />}
  </div>;
}
